version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - "./sql/:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: restu_db
    ports: 
      - 3306:3306
    expose:
      - 3306
  web:
    build: .
    environment: 
      DB_HOST: "db"
    depends_on:
      - "db"
    ports:
      - "3000:3000"
