version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@local.dev
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - 3069:80
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: resturanteer
    ports:
      - 5432:5432
  web:
    build: 
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/resturanteer?schema=public
    volumes:
      - "../:/usr/src/app"
    ports:
      - "3000:3000"
      - "5000:5000"
      - "9229:9229"
      - "35729:35729"
