version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@local.dev
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - 3069:80
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: resturanteer
    ports:
      - 5432:5432
  db:
    image: mysql:8.0.26
    volumes:
      - "../sql/:/docker-entrypoint-initdb.d"
      - "../sql/:/sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: restu_db
    ports: 
      - 3306:3306
    expose:
      - 3306
  web:
    build: 
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      DB_HOST: "db"
    volumes:
      - "../:/usr/src/app"
    depends_on:
      - "db"
    ports:
      - "3000:3000"
      - "9229:9229"
      - "35729:35729"
